# see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases
jobs:

# Provide a name for the job
- job: Linux
  displayName: ubuntu
  timeoutInMinutes: 0
  strategy:
    parallel: 10

  pool:
    vmImage: 'ubuntu-latest'

  steps:
    - script: sudo dpkg --add-architecture i386 && sudo apt-get update
      displayName: 'apt add architecture'

    - script: sudo apt install autogen automake bc bison build-essential check cmake curl cython debootstrap expect flex g++-multilib gettext git gperf imagemagick intltool libbz2-dev libc6-i386 libcppunit-dev libffi-dev libgc-dev libgmp3-dev libltdl-dev libmount-dev libncurses-dev libpcre3-dev libssl-dev libtool libunistring-dev lzip mercurial ncurses-dev php pkg-config python3 python3-distutils scons subversion swig unzip xmlto zlib1g-dev
      displayName: 'apt install'

    - script: python -m pip install --upgrade pip && pip install -U setuptools pip wheel httpie
      displayName: 'Install Python dependencies'
  

    - script: make setup
      displayName: 'make'

    - script: make pos=$(System.JobPositionInPhase) total=$(System.TotalJobsInPhase) all-archs-latest
      displayName: 'make'
      workingDirectory: spk/urbackup
  
#    - task: PublishPipelineArtifact@1
#      inputs:
#        targetPath: '$(Build.SourcesDirectory)/packages'
#        artifact: 'Packages$(System.JobPositionInPhase)'
#        publishLocation: 'pipeline'
 
    - task: GitHubRelease@1
      inputs:
        gitHubConnection: 'github2'
        repositoryName: 'josef109/spksrc'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'gitTag'
        assets: '$(Build.Repository.LocalPath)/packages/*.spk'
        addChangeLog: false'


 
