# see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases
jobs:

# Provide a name for the job
- job: Linux
  displayName: ubuntu
  timeoutInMinutes: 0
  strategy:
    matrix: 
      arch-qoriq-6.1 
      arch-kvmx64-6.1
      arch-armv7-6.1
      arch-denverton-6.1
      arch-x64-6.1
      arch-broadwell-6.1 
      arch-aarch64-6.1 
      arch-avoton-6.1 
      arch-armada38x-6.1 
      arch-x86-6.1 
      arch-88f6281-6.1 
      arch-grantley-6.1 
      arch-braswell-6.1 
      arch-comcerto2k-6.1 
      arch-armadaxp-6.1
      arch-hi3535-6.1 
      arch-dockerx64-6.1 
      arch-cedarview-6.1 
      arch-armada375-6.1 
      arch-rtd1296-6.1
      arch-monaco-6.1 
      arch-apollolake-6.1 
      arch-bromolow-6.1 
      arch-alpine-6.1 
      arch-armada370-6.1
      arch-evansport-6.1
    maxParallel: 10

  pool:
    vmImage: 'ubuntu-latest'

  steps:
    - script: sudo dpkg --add-architecture i386 && sudo apt-get update
      displayName: 'apt add architecture'

    - script: sudo apt install autogen automake bc bison build-essential check cmake curl cython debootstrap expect flex g++-multilib gettext git gperf imagemagick intltool libbz2-dev libc6-i386 libcppunit-dev libffi-dev libgc-dev libgmp3-dev libltdl-dev libmount-dev libncurses-dev libpcre3-dev libssl-dev libtool libunistring-dev lzip mercurial ncurses-dev php pkg-config python3 python3-distutils scons subversion swig unzip xmlto zlib1g-dev
      displayName: 'apt install'

    - script: python -m pip install --upgrade pip && pip install -U setuptools pip wheel httpie
      displayName: 'Install Python dependencies'
  

    - script: make setup
      displayName: 'make setup'

    - script: make $(System.JobName) 
      displayName: 'make $(System.JobName)'
      workingDirectory: spk/urbackup
  

    - task: GitHubRelease@1
      inputs:
        gitHubConnection: 'github'
        repositoryName: 'josef109/spksrc'
        action: edit
        target: '$(Build.SourceVersion)'
        tagSource: userSpecifiedTag
        tag: '2.4.12'
        assets: '$(Build.Repository.LocalPath)/packages/*.spk'
        assetUploadMode: replace
        addChangeLog: false


 
