# see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases
jobs:

  # Provide a name for the job
  - job: Linux
    displayName: ubuntu
    timeoutInMinutes: 0
    strategy:
      matrix: 
        qoriq:
          architecure: arch-qoriq-6.1
        kvmx64:
          architecure: arch-kvmx64-6.1
        armv7:
          architecure: arch-armv7-6.1
        denverton:
          architecure: arch-denverton-6.1
        x64:
          architecure: arch-x64-6.1
        broadwell:
          architecure: arch-broadwell-6.1
        aarch64:
          architecure: arch-aarch64-6.1
        avoton:
          architecure: arch-avoton-6.1
        armada38x:
          architecure: arch-armada38x-6.1
        x86:
          architecure: arch-x86-6.1
        88f6281:
          architecure: arch-88f6281-6.1
        grantley:
          architecure: arch-grantley-6.1
        braswell:
          architecure: arch-braswell-6.1
        comcerto2k:
          architecure: arch-comcerto2k-6.1
        armadaxp:
          architecure: arch-armadaxp-6.1
        hi3535:
          architecure: arch-hi3535-6.1
        dockerx64:
          architecure: arch-dockerx64-6.1
        cedarview:
          architecure: arch-cedarview-6.1
        armada375:
          architecure: arch-armada375-6.1
        rtd1296:
          architecure: arch-rtd1296-6.1
        monaco:
          architecure: arch-monaco-6.1
        apollolake:
          architecure: arch-apollolake-6.1
        bromolow:
          architecure: arch-bromolow-6.1
        alpine:
          architecure: arch-alpine-6.1
        armada370:
          architecure: arch-armada370-6.1
        evansport:
          architecure: arch-evansport-6.1    

      maxParallel: 10
  
    pool:
      vmImage: 'ubuntu-latest'
  
    steps:
      - script: sudo dpkg --add-architecture i386 && sudo apt-get update
        displayName: 'apt add architecture'
  
      - script: sudo apt install autogen automake bc bison build-essential check cmake curl cython debootstrap expect flex g++-multilib gettext git gperf imagemagick intltool libbz2-dev libc6-i386 libcppunit-dev libffi-dev libgc-dev libgmp3-dev libltdl-dev libmount-dev libncurses-dev libpcre3-dev libssl-dev libtool libunistring-dev lzip mercurial ncurses-dev php pkg-config python3 python3-distutils scons subversion swig unzip xmlto zlib1g-dev
        displayName: 'apt install'
  
      - script: python -m pip install --upgrade pip && pip install -U setuptools pip wheel httpie
        displayName: 'Install Python dependencies'
    
  
      - script: make setup
        displayName: 'make setup'
  
      - script: make $(architecure) 
        displayName: 'make $(architecure)'
        workingDirectory: spk/urbackup
    
  
      - task: GitHubRelease@1
        inputs:
          gitHubConnection: 'github'
          repositoryName: 'josef109/spksrc'
          action: edit
          target: '$(Build.SourceVersion)'
          tagSource: userSpecifiedTag
          tag: '2.4.12'
          assets: '$(Build.Repository.LocalPath)/packages/*.spk'
          assetUploadMode: replace
          addChangeLog: false
  
  
   
  